# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/surat-backend-app:$COMMIT_SHA'
      - '.'
    id: 'Build Docker Image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/surat-backend-app:$COMMIT_SHA'
    id: 'Push Docker Image'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'surat-backend-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/surat-backend-app:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - |
        NODE_ENV=production,
        PORT=3000,
        GCS_BUCKET_NAME=c-01-450604, # INI TETAP KE PROYEK TEMAN ANDA
        GCP_PROJECT_ID=c-01-450604,  # INI TETAP KE PROYEK TEMAN ANDA
        GCP_CLIENT_EMAIL=storage-uploader-service@c-01-450604.iam.gserviceaccount.com # INI TETAP KE PROYEK TEMAN ANDA
    secretEnv: ['MYSQL_DATABASE_URL', 'POSTGRES_DATABASE_URL', 'JWT_SECRET', 'GCP_PRIVATE_KEY']
    id: 'Deploy to Cloud Run'

availableSecrets:
  secretManager:
    # Secret ini dibuat di proyek Anda (A-08), jadi ID proyek di sini harus ID proyek Anda.
    - versionName: projects/[YOUR_A-08_PROJECT_ID]/secrets/MYSQL_DATABASE_URL_SECRET/versions/latest
      env: 'MYSQL_DATABASE_URL'
    - versionName: projects/[YOUR_A-08_PROJECT_ID]/secrets/POSTGRES_DATABASE_URL_SECRET/versions/latest
      env: 'POSTGRES_DATABASE_URL'
    - versionName: projects/[YOUR_A-08_PROJECT_ID]/secrets/JWT_SECRET_KEY/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/[YOUR_A-08_PROJECT_ID]/secrets/GCP_PRIVATE_KEY_SECRET/versions/latest
      env: 'GCP_PRIVATE_KEY'