steps:
  # Step 1: Build Docker image dari Dockerfile Anda
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/surat-backend", 
        ".",
      ]
    dir: "." 

  # Step 2: Push Docker image yang sudah dibangun ke Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/surat-backend"]

  # Step 3: Deploy image ke Google Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud 
    args:
      [
        "run",
        "deploy",
        "surat-backend-service", 
        "--image",
        "gcr.io/$PROJECT_ID/surat-backend", 
        "--timeout",
        "1000s",
        "--port",
        "3000", 
        "--region",
        "us-central1", 
        "--allow-unauthenticated", 
        "--set-secrets", 
        "JWT_SECRET=${projects/$PROJECT_ID/secrets/JWT_SECRET_KEY/versions/latest},MYSQL_DATABASE_URL=${projects/$PROJECT_ID/secrets/MYSQL_DATABASE_URL_SECRET/versions/latest},POSTGRES_DATABASE_URL=${projects/$PROJECT_ID/secrets/POSTGRES_DATABASE_URL_SECRET/versions/latest},GCP_PRIVATE_KEY=${projects/$PROJECT_ID/secrets/GCP_PRIVATE_KEY_SECRET/versions/latest}",
        "--set-env-vars", 
        "NODE_ENV=production,GCS_BUCKET_NAME=c-01-450604,GCP_PROJECT_ID=c-01-450604,GCP_CLIENT_EMAIL=storage-uploader-service@c-01-450604.iam.gserviceaccount.com" 
      ]

# Opsi logging untuk Cloud Build
options:
  logging: CLOUD_LOGGING_ONLY

# Konfigurasi Secret Manager untuk Cloud Build
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET_KEY/versions/latest
      env: JWT_SECRET_KEY_SECRET_MANAGER_VALUE 
    - versionName: projects/$PROJECT_ID/secrets/MYSQL_DATABASE_URL_SECRET/versions/latest
      env: MYSQL_DATABASE_URL_SECRET_MANAGER_VALUE
    - versionName: projects/$PROJECT_ID/secrets/POSTGRES_DATABASE_URL_SECRET/versions/latest
      env: POSTGRES_DATABASE_URL_SECRET_MANAGER_VALUE
    - versionName: projects/$PROJECT_ID/secrets/GCP_PRIVATE_KEY_SECRET/versions/latest
      env: GCP_PRIVATE_KEY_SECRET_MANAGER_VALUE