# cloudbuild.yaml
# Menggunakan opsi logging langsung ke Cloud Logging, yang mengatasi error logsBucket
options:
  logging: CLOUD_LOGGING_ONLY # Ini akan mengirim log build langsung ke Cloud Logging

steps:
  # Step 1: Build the Docker image
  # Menggunakan Artifact Registry dan nama aplikasi yang baru
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/surat-backend-app:$COMMIT_SHA'
      - '.'
    dir: "." # Dari YAML lama Anda, menunjukkan Dockerfile ada di root
    id: 'Build Docker Image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/surat-backend-app:$COMMIT_SHA'
    id: 'Push Docker Image'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud # entrypoint dari YAML lama
    args:
      - 'run'
      - 'deploy'
      - 'surat-backend-app' # Nama layanan Cloud Run yang baru
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/surat-backend-app:$COMMIT_SHA'
      - '--timeout'
      - '1000s' # Timeout dari YAML lama Anda
      - '--port'
      - '3000' # Port yang sesuai untuk aplikasi Anda (bukan 5000)
      - '--region'
      - 'us-central1' # Wilayah deployment Cloud Run Anda
      - '--allow-unauthenticated' # Dari YAML lama Anda
      - '--set-env-vars' # Menggunakan set-env-vars dan secretEnv untuk variabel
      - | # Mengatur variabel lingkungan langsung (untuk yang tidak sensitif)
        NODE_ENV=production,
        PORT=3000,
        GCS_BUCKET_NAME=c-01-450604, # Ini tetap ke proyek teman Anda
        GCP_PROJECT_ID=c-01-450604,  # Ini tetap ke proyek teman Anda
        GCP_CLIENT_EMAIL=storage-uploader-service@c-01-450604.iam.gserviceaccount.com # Ini tetap ke proyek teman Anda
    secretEnv: ['MYSQL_DATABASE_URL', 'POSTGRES_DATABASE_URL', 'JWT_SECRET', 'GCP_PRIVATE_KEY']
    id: 'Deploy to Cloud Run'

# Bagian ini mendefinisikan secret yang tersedia dari Secret Manager
# Secret-secret ini dibuat di proyek Anda (a-08-450504), jadi Project ID di sini harus ID proyek Anda.
availableSecrets:
  secretManager:
    - versionName: projects/a-08-450504/secrets/MYSQL_DATABASE_URL_SECRET/versions/latest
      env: 'MYSQL_DATABASE_URL'
    - versionName: projects/a-08-450504/secrets/POSTGRES_DATABASE_URL_SECRET/versions/latest
      env: 'POSTGRES_DATABASE_URL'
    - versionName: projects/a-08-450504/secrets/JWT_SECRET_KEY/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/a-08-450504/secrets/GCP_PRIVATE_KEY_SECRET/versions/latest
      env: 'GCP_PRIVATE_KEY'