steps:
  # Step 1: Build Docker image dari Dockerfile Anda
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/surat-backend", 
        ".",
      ]
    dir: "." 

  # Step 2: Push Docker image yang sudah dibangun ke Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/surat-backend"]

  # Step 3: Deploy image ke Google Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud 
    args:
      [
        "run",
        "deploy",
        "surat-backend-service", 
        "--image",
        "gcr.io/$PROJECT_ID/surat-backend", 
        "--timeout",
        "1000s",
        "--port",
        "3000", 
        "--region",
        "us-central1", 
        "--allow-unauthenticated", 
        "--set-secrets", 
        "JWT_SECRET=JWT_SECRET_KEY:latest,MYSQL_DATABASE_URL=MYSQL_DATABASE_URL_SECRET:latest,POSTGRES_DATABASE_URL=POSTGRES_DATABASE_URL_SECRET:latest,GCP_PRIVATE_KEY=GCP_PRIVATE_KEY_SECRET:latest",
        "--set-env-vars", 
        "NODE_ENV=production,GCS_BUCKET_NAME=c-01-450604,GCP_PROJECT_ID=c-01-450604,GCP_CLIENT_EMAIL=storage-uploader-service@c-01-450604.iam.gserviceaccount.com" 
      ]

# Opsi logging untuk Cloud Build
options:
  logging: CLOUD_LOGGING_ONLY

